include /ms/dev/elfms/ms/1.0/src/make.rules

MSPERLFILES = \
	$(INSTALLDIR)/common/sbin/aii-dhcp \
	$(INSTALLDIR)/common/sbin/aii-installack.cgi \
	$(INSTALLDIR)/common/sbin/aii-installfe \
	$(INSTALLDIR)/common/sbin/aii-nbp \
	$(INSTALLDIR)/common/sbin/aii-osinstall \
	$(INSTALLDIR)/common/sbin/aii-shellfe

